# Generated by Django 4.2.1 on 2023-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidate_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_pic',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='img/company/hr'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='img/company/logo'),
        ),
    ]
