# Generated by Django 4.2.1 on 2023-06-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_hr_pic_alter_company_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hr_pic',
        ),
    ]
