# Generated by Django 4.2.1 on 2023-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_company_hr_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_pic',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='img/company/hr'),
        ),
    ]
