# Generated by Django 4.2.1 on 2023-06-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobdetails_experience_alter_jobdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='img/jobpost'),
        ),
    ]
