# Generated by Django 4.2.1 on 2023-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobdetails_company_id_jobdetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default=None, upload_to='img/jobpost'),
        ),
    ]
