# Generated by Django 4.2.1 on 2023-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobdetails_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobtype',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
